### ISSUE TITLE
Healthcheck is false - mysqld did not start correctly

### ISSUE THREAD

**Issue by chrbayer** [ONLYOFFICE/snap-documentserver#93] opened 2022-03-04 09:07 UTC
In version 63 and 66, document server does not work anymore, healthcheck is false.

Checking some log files, I have the following finding: mysqld has not been started, port is Ok and free but daemon not started.

The logs tell me about some missing plugin libs and an needed update of database tables:

```
2022-03-04T07:58:54.656015Z mysqld_safe Logging to '/var/snap/onlyoffice-ds/66/mysql/error.log'.
2022-03-04T07:58:54.656015Z mysqld_safe Logging to '/var/snap/onlyoffice-ds/66/mysql/error.log'.
2022-03-04T07:58:54.672427Z mysqld_safe Starting mysqld daemon with databases from /var/snap/onlyoffice-ds/66/mysql
2022-03-04T07:58:54.672427Z mysqld_safe Starting mysqld daemon with databases from /var/snap/onlyoffice-ds/66/mysql
2022-03-04T07:58:54.843155Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-03-04T07:58:54.843211Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
2022-03-04T07:58:54.843228Z 0 [Note] /snap/onlyoffice-ds/66/bin/mysqld (mysqld 5.7.27) starting as process 3561687 ...
2022-03-04T07:58:54.845955Z 0 [Note] InnoDB: PUNCH HOLE support available
2022-03-04T07:58:54.845973Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-03-04T07:58:54.845976Z 0 [Note] InnoDB: Uses event mutexes
2022-03-04T07:58:54.845979Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2022-03-04T07:58:54.845981Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-03-04T07:58:54.845983Z 0 [Note] InnoDB: Using Linux native AIO
2022-03-04T07:58:54.846146Z 0 [Note] InnoDB: Number of pools: 1
2022-03-04T07:58:54.846214Z 0 [Note] InnoDB: Using CPU crc32 instructions
2022-03-04T07:58:54.847198Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-03-04T07:58:54.853152Z 0 [Note] InnoDB: Completed initialization of buffer pool
2022-03-04T07:58:54.866148Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2022-03-04T07:58:54.871791Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-03-04T07:58:54.871868Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-03-04T07:58:54.902490Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-03-04T07:58:54.903042Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2022-03-04T07:58:54.903049Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2022-03-04T07:58:54.903241Z 0 [Note] InnoDB: Waiting for purge to start
2022-03-04T07:58:54.953384Z 0 [Note] InnoDB: 5.7.27 started; log sequence number 1210075
2022-03-04T07:58:54.953537Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/snap/onlyoffice-ds/66/mysql/ib_buffer_pool
2022-03-04T07:58:54.953597Z 0 [Note] InnoDB: Buffer pool(s) load completed at 220304  8:58:54
2022-03-04T07:58:54.953669Z 0 [ERROR] Can't open shared library '/snap/onlyoffice-ds/66/lib/plugin/provider_bzip2' (errno: 2 /snap/onlyoffice-ds/66/lib/plugin/provider_bzip2: cannot open shared object file: No such file or directory)
2022-03-04T07:58:54.953675Z 0 [ERROR] Couldn't load plugin named 'provider_bzip2' with soname 'provider_bzip2'.
2022-03-04T07:58:54.953683Z 0 [ERROR] Can't open shared library '/snap/onlyoffice-ds/66/lib/plugin/provider_lz4' (errno: 2 /snap/onlyoffice-ds/66/lib/plugin/provider_lz4: cannot open shared object file: No such file or directory)
2022-03-04T07:58:54.953685Z 0 [ERROR] Couldn't load plugin named 'provider_lz4' with soname 'provider_lz4'.
2022-03-04T07:58:54.953691Z 0 [ERROR] Can't open shared library '/snap/onlyoffice-ds/66/lib/plugin/provider_lzma' (errno: 2 /snap/onlyoffice-ds/66/lib/plugin/provider_lzma: cannot open shared object file: No such file or directory)
2022-03-04T07:58:54.953693Z 0 [ERROR] Couldn't load plugin named 'provider_lzma' with soname 'provider_lzma'.
mysqld: Table 'mysql.plugin' doesn't exist
2022-03-04T07:58:54.953739Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
2022-03-04T07:58:54.953794Z 0 [ERROR] unknown variable 'provider_bzip2=force_plus_permanent'
2022-03-04T07:58:54.953797Z 0 [ERROR] Aborting

2022-03-04T07:58:54.953801Z 0 [Note] Binlog end
2022-03-04T07:58:54.953823Z 0 [Note] Shutting down plugin 'ngram'
2022-03-04T07:58:54.953826Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2022-03-04T07:58:54.953852Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2022-03-04T07:58:54.953854Z 0 [Note] Shutting down plugin 'MyISAM'
2022-03-04T07:58:54.953859Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2022-03-04T07:58:54.953861Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2022-03-04T07:58:54.953862Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2022-03-04T07:58:54.953864Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2022-03-04T07:58:54.953865Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2022-03-04T07:58:54.953867Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2022-03-04T07:58:54.953868Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2022-03-04T07:58:54.953870Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2022-03-04T07:58:54.953871Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2022-03-04T07:58:54.953873Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2022-03-04T07:58:54.953874Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2022-03-04T07:58:54.953876Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2022-03-04T07:58:54.953878Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2022-03-04T07:58:54.953879Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2022-03-04T07:58:54.953881Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2022-03-04T07:58:54.953882Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2022-03-04T07:58:54.953884Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2022-03-04T07:58:54.953890Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2022-03-04T07:58:54.953891Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2022-03-04T07:58:54.953893Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2022-03-04T07:58:54.953894Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2022-03-04T07:58:54.953896Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2022-03-04T07:58:54.953897Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2022-03-04T07:58:54.953899Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2022-03-04T07:58:54.953900Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2022-03-04T07:58:54.953902Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2022-03-04T07:58:54.953904Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2022-03-04T07:58:54.953905Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2022-03-04T07:58:54.953907Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2022-03-04T07:58:54.953908Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2022-03-04T07:58:54.953910Z 0 [Note] Shutting down plugin 'InnoDB'
2022-03-04T07:58:54.953970Z 0 [Note] InnoDB: FTS optimize thread exiting.
2022-03-04T07:58:54.954040Z 0 [Note] InnoDB: Starting shutdown...
2022-03-04T07:58:55.054198Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/snap/onlyoffice-ds/66/mysql/ib_buffer_pool
2022-03-04T07:58:55.054307Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 220304  8:58:55
2022-03-04T07:58:56.560086Z 0 [Note] InnoDB: Shutdown completed; log sequence number 1210094
2022-03-04T07:58:56.560936Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-03-04T07:58:56.560945Z 0 [Note] Shutting down plugin 'MEMORY'
2022-03-04T07:58:56.560949Z 0 [Note] Shutting down plugin 'CSV'
2022-03-04T07:58:56.560951Z 0 [Note] Shutting down plugin 'sha256_password'
2022-03-04T07:58:56.560953Z 0 [Note] Shutting down plugin 'mysql_native_password'
2022-03-04T07:58:56.561038Z 0 [Note] Shutting down plugin 'binlog'
2022-03-04T07:58:56.561122Z 0 [Note] /snap/onlyoffice-ds/66/bin/mysqld: Shutdown complete

2022-03-04T07:58:56.598779Z mysqld_safe mysqld from pid file /tmp/pids/mysql.pid ended
2022-03-04T07:58:56.598779Z mysqld_safe mysqld from pid file /tmp/pids/mysql.pid ended
```

**Comment by igwyd** [comment] 2022-03-04 10:18
@chrbayer hello, i can't reproduce your mysql error. I think it's your server, permissions or a previous installations. Fist of all try clear install onlyoffice:
1. remove with purge ```sudo snap remove --purge onlyoffice-ds```
2. install ```sudo snap install onlyoffice-ds```

If that doesn't help, decribe more detail your setup: server version, snap version and all what you think may important.

**Comment by chrbayer** [comment] 2022-03-04 13:49
@igwyd Thanks for your help!

Purging everything didn't help, after all settings where in place again (certs, ports and jwt stuff), I have the same problem, the mysqld has not been started and the healthcheck is correctly false...

My server is running Arch Linux with kernel 5.16.11-arch1-2, I have an mariadb server running at port 3306, port OO mysqld is set to 3307. Snap version is 2.24.4... I don't know what else could be relevant...

**Comment by totten** [comment] 2022-03-29 03:09
> ```
> 2022-03-04T07:58:54.953794Z 0 [ERROR] unknown variable 'provider_bzip2=force_plus_permanent'
> ```

Came across this page while debugging a completely different app with a similar error message from another arch user. (I don't use arch or onlyoffice.)

Arch includes a config file `provider_bzip2` on its own builds of MySQL/MariaDB (https://archlinux.org/packages/extra/x86_64/mariadb/files/). If you are trying to run a secondary copy of MySQL in a half-isolated environment (eg a "snap" package?), then be aware that mysql binaries often have a strong preference for reading the system-wide `/etc/my.cnf`. 

We haven't seen this conflict on Debian/Ubuntu -- probably because Debian puts the config in a different place (`/etc/mysql/my.cnf`). On Debian hosts, `/etc/my.cnf` is always blank.

You might want to audit the calls to `mysql`, `mysqld`, `mysql_install_db`, or similar and see if they need an extra guard (eg `--no-defaults` or `--defaults-file`).

**Comment by chrbayer** [comment] 2022-03-29 06:38
@totten Thank you for this hint!

I temporally renamed the system mysql configuration files, I don't get this error but a different one. So this seems to be the root cause of my reported problem.

The new error log is:

```
2022-03-29T06:22:52.065485Z mysqld_safe Logging to '/var/snap/onlyoffice-ds/67/mysql/error.log'.
2022-03-29T06:22:52.065485Z mysqld_safe Logging to '/var/snap/onlyoffice-ds/67/mysql/error.log'.
2022-03-29T06:22:52.082471Z mysqld_safe Starting mysqld daemon with databases from /var/snap/onlyoffice-ds/67/mysql
2022-03-29T06:22:52.082471Z mysqld_safe Starting mysqld daemon with databases from /var/snap/onlyoffice-ds/67/mysql
2022-03-29T06:22:52.262960Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-03-29T06:22:52.263017Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
2022-03-29T06:22:52.263037Z 0 [Note] /snap/onlyoffice-ds/67/bin/mysqld (mysqld 5.7.27) starting as process 3603793 ...
2022-03-29T06:22:52.265919Z 0 [Note] InnoDB: PUNCH HOLE support available
2022-03-29T06:22:52.265934Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-03-29T06:22:52.265937Z 0 [Note] InnoDB: Uses event mutexes
2022-03-29T06:22:52.265939Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2022-03-29T06:22:52.265941Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-03-29T06:22:52.265944Z 0 [Note] InnoDB: Using Linux native AIO
2022-03-29T06:22:52.266139Z 0 [Note] InnoDB: Number of pools: 1
2022-03-29T06:22:52.266218Z 0 [Note] InnoDB: Using CPU crc32 instructions
2022-03-29T06:22:52.267362Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-03-29T06:22:52.273465Z 0 [Note] InnoDB: Completed initialization of buffer pool
2022-03-29T06:22:52.285095Z 0 [Note] InnoDB: The first innodb_system data file 'ibdata1' did not exist. A new tablespace will be created!
2022-03-29T06:22:52.285315Z 0 [Note] InnoDB: Setting file './ibdata1' size to 12 MB. Physically writing the file full; Please wait ...
2022-03-29T06:22:52.317781Z 0 [Note] InnoDB: File './ibdata1' size is now 12 MB.
2022-03-29T06:22:52.318049Z 0 [Note] InnoDB: Setting log file ./ib_logfile101 size to 48 MB
2022-03-29T06:22:52.434920Z 0 [Note] InnoDB: Setting log file ./ib_logfile1 size to 48 MB
2022-03-29T06:22:52.558462Z 0 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
2022-03-29T06:22:52.558501Z 0 [Warning] InnoDB: New log files created, LSN=45790
2022-03-29T06:22:52.558509Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-03-29T06:22:52.558540Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-03-29T06:22:52.589949Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-03-29T06:22:52.590117Z 0 [Note] InnoDB: Doublewrite buffer not found: creating new
2022-03-29T06:22:52.605105Z 0 [Note] InnoDB: Doublewrite buffer created
2022-03-29T06:22:52.609341Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2022-03-29T06:22:52.609351Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2022-03-29T06:22:52.609517Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2022-03-29T06:22:52.615645Z 0 [Note] InnoDB: Foreign key constraint system tables created
2022-03-29T06:22:52.615693Z 0 [Note] InnoDB: Creating tablespace and datafile system tables.
2022-03-29T06:22:52.617787Z 0 [Note] InnoDB: Tablespace and datafile system tables created.
2022-03-29T06:22:52.617835Z 0 [Note] InnoDB: Creating sys_virtual system tables.
2022-03-29T06:22:52.619577Z 0 [Note] InnoDB: sys_virtual table created
2022-03-29T06:22:52.619747Z 0 [Note] InnoDB: Waiting for purge to start
2022-03-29T06:22:52.670035Z 0 [Note] InnoDB: 5.7.27 started; log sequence number 0
mysqld: Table 'mysql.plugin' doesn't exist
2022-03-29T06:22:52.670804Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
2022-03-29T06:22:52.671309Z 0 [Note] Salting uuid generator variables, current_pid: 3603793, server_start_time: 1648534972, bytes_sent: 0,
2022-03-29T06:22:52.671382Z 0 [Note] Generated uuid: 'a9f6b7c9-af28-11ec-b963-1402ec31cd77', server_start_time: 18253370766361469709, bytes_sent: 94174007725104
2022-03-29T06:22:52.671410Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: a9f6b7c9-af28-11ec-b963-1402ec31cd77.
2022-03-29T06:22:52.674388Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2022-03-29T06:22:52.674515Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2022-03-29T06:22:52.674526Z 0 [Note] Server hostname (bind-address): '*'; port: 3307
2022-03-29T06:22:52.674578Z 0 [Note] IPv6 is available.
2022-03-29T06:22:52.674587Z 0 [Note]   - '::' resolves to '::';
2022-03-29T06:22:52.674660Z 0 [Note] Server socket created on IP: '::'.
2022-03-29T06:22:52.674899Z 0 [Warning] Failed to open optimizer cost constant tables

2022-03-29T06:22:52.675038Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
2022-03-29T06:22:52.675055Z 0 [ERROR] Fatal error: Failed to initialize ACL/grant/time zones structures or failed to remove temporary table files.
2022-03-29T06:22:52.675109Z 0 [ERROR] Aborting

2022-03-29T06:22:52.675144Z 0 [Note] Binlog end
2022-03-29T06:22:52.675201Z 0 [Note] Shutting down plugin 'ngram'
2022-03-29T06:22:52.675208Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2022-03-29T06:22:52.675280Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2022-03-29T06:22:52.675285Z 0 [Note] Shutting down plugin 'MyISAM'
2022-03-29T06:22:52.675301Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2022-03-29T06:22:52.675306Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2022-03-29T06:22:52.675310Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2022-03-29T06:22:52.675314Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2022-03-29T06:22:52.675319Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2022-03-29T06:22:52.675323Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2022-03-29T06:22:52.675327Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2022-03-29T06:22:52.675331Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2022-03-29T06:22:52.675335Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2022-03-29T06:22:52.675339Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2022-03-29T06:22:52.675344Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2022-03-29T06:22:52.675348Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2022-03-29T06:22:52.675352Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2022-03-29T06:22:52.675356Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2022-03-29T06:22:52.675360Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2022-03-29T06:22:52.675365Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2022-03-29T06:22:52.675369Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2022-03-29T06:22:52.675373Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2022-03-29T06:22:52.675377Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2022-03-29T06:22:52.675382Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2022-03-29T06:22:52.675386Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2022-03-29T06:22:52.675390Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2022-03-29T06:22:52.675394Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2022-03-29T06:22:52.675398Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2022-03-29T06:22:52.675402Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2022-03-29T06:22:52.675407Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2022-03-29T06:22:52.675411Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2022-03-29T06:22:52.675415Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2022-03-29T06:22:52.675419Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2022-03-29T06:22:52.675423Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2022-03-29T06:22:52.675427Z 0 [Note] Shutting down plugin 'InnoDB'
2022-03-29T06:22:52.675549Z 0 [Note] InnoDB: FTS optimize thread exiting.
2022-03-29T06:22:52.675768Z 0 [Note] InnoDB: Starting shutdown...
2022-03-29T06:22:52.776114Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/snap/onlyoffice-ds/67/mysql/ib_buffer_pool
2022-03-29T06:22:52.776383Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 220329  8:22:52
2022-03-29T06:22:54.487616Z 0 [Note] InnoDB: Shutdown completed; log sequence number 1209961
2022-03-29T06:22:54.489709Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-03-29T06:22:54.489731Z 0 [Note] Shutting down plugin 'MEMORY'
2022-03-29T06:22:54.489739Z 0 [Note] Shutting down plugin 'CSV'
2022-03-29T06:22:54.489746Z 0 [Note] Shutting down plugin 'sha256_password'
2022-03-29T06:22:54.489751Z 0 [Note] Shutting down plugin 'mysql_native_password'
2022-03-29T06:22:54.489965Z 0 [Note] Shutting down plugin 'binlog'
2022-03-29T06:22:54.490193Z 0 [Note] /snap/onlyoffice-ds/67/bin/mysqld: Shutdown complete
```

**Comment by igwyd** [comment] 2022-04-04 13:23
@chrbayer i reproduce it on Arch Linux and create issue 56453 in our private issue tracker. Thank you for report.

**Comment by igwyd** [comment] 2022-06-20 17:05
It's fixed at: https://github.com/ONLYOFFICE/snap-documentserver/commit/119db53e989d9517635a227198537695d837e1ea
And will be released in the next release.

**Comment by chrbayer** [comment] 2022-06-20 21:44
That are great news, thanks :-)

**Comment by ShockwaveNN** [comment] 2022-08-15 07:49
I'll close this issue, since fix should be released

**Closed by ShockwaveNN** 2022-08-15 07:49 UTC
Labels: bug, fixed
