### ISSUE TITLE
Unable to change HTTPS port.

### ISSUE THREAD

**Issue by Andy-EOS** [ONLYOFFICE/snap-documentserver#33] opened 2020-02-19 19:31 UTC
The document server works perfectly on port 443. The command 'snap set onlyoffice-ds onlyoffice.ds-ssl-port=444' provides the following output:

Run configure hook of "onlyoffice-ds" snap
restart of [onlyoffice-ds.documentserver]                                                                              ^[[0m^[[?25h^[[K

The server continues to run on port 443. I've tried restarting the snap after making this change. I've tried multiple other ports (many of them above 1024) with the same results.

OS: Ubuntu 18.04

Update: 
I've just tried updating '/var/snap/onlyoffice-ds/10/etc/onlyoffice/documentserver/nginx/ds.conf' manually. Changes to the HTTP port are kept when restarting the snap. Changes to the HTTPS port seem to be written back to 443.

**Comment by philkman** [comment] 2020-02-25 09:59
I can confirm the issues, also running Ubuntu 18.04

**Comment by GarethFromWales** [comment] 2020-03-07 12:05
Same issue here running Ubuntu 18.04

**Comment by leadermontanus** [comment] 2020-05-10 19:06
Can confirm this on Ubuntu 20.04 (recent, fresh install).

My workaround for the time being is to use port 444 for the other service wanting to use 443 (nextcloud in this case) and then use the port forwarding in the router to swap ports 444 and 443.

**Comment by gb-123-git** [comment] 2020-08-04 20:05
+1 (on Ubuntu 18.04)
Workaround may be to edit the ds.conf manually.

**Comment by ShanmuHuang** [comment] 2020-09-02 08:54
Same issue here running Ubuntu 20.04

**Comment by pabloVoorvaart** [comment] 2020-09-07 10:47
I can also confirm this is broken on Ubuntu 20.04, running onlyoffice snap version 5.4.0.

 Editing ds.conf will be overwritten on service restart, so im guessing this setting is stored somewhere, but i cant figure out where. I was looking at the configure hook, dunno if that get exeuted on service restart.

**Comment by VecH** [comment] 2020-09-28 06:04
20.04
`
root@nc:/var/snap/onlyoffice-ds# lsb_release -h
Usage: lsb_release [options]

Options:
  -h, --help         show this help message and exit
  -v, --version      show LSB modules this system supports
  -i, --id           show distributor ID
  -d, --description  show description of this distribution
  -r, --release      show release number of this distribution
  -c, --codename     show code name of this distribution
  -a, --all          show all of the above information
  -s, --short        show requested information in short format
root@nc:/var/snap/onlyoffice-ds# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
root@nc:/var/snap/onlyoffice-ds# uname -a
Linux nc 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@nc:/var/snap/onlyoffice-ds# snap info onlyoffice-ds
name:      onlyoffice-ds
summary:   An online office suite that allowing to create, view and edit documents.
publisher: Ascensio System SIA (onlyoffice✓)
store-url: https://snapcraft.io/onlyoffice-ds
contact:   https://github.com/ONLYOFFICE/snap-documentserver/issues
license:   unset
description: |
  ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts,
  spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx
  and enabling collaborative editing in real time.
commands:
  - onlyoffice-ds.mysql-client
  - onlyoffice-ds.mysqldump
  - onlyoffice-ds.node
services:
  onlyoffice-ds.documentserver: simple, enabled, active
  onlyoffice-ds.mysql:          simple, enabled, active
  onlyoffice-ds.nginx:          simple, enabled, active
  onlyoffice-ds.rabbitmq:       simple, enabled, active
  onlyoffice-ds.redis:          simple, enabled, active
snap-id:      zZWL0GK8BltYmYJcaTUQro9X2Rd6yVaN
tracking:     latest/stable
refresh-date: 8 days ago, at 21:18 +09
channels:
  latest/stable:    5.4.0 2019-10-28 (10) 595MB -
  latest/candidate: 5.4.0 2019-10-28 (10) 595MB -
  latest/beta:      5.4.0 2019-10-24 (10) 595MB -
  latest/edge:      5.6.5 2020-09-22 (21) 748MB -
installed:          5.4.0            (10) 595MB -
root@nc:/var/snap/onlyoffice-ds# snap get onlyoffice-ds onlyoffice.ds-ssl-port
445
root@nc:/var/snap/onlyoffice-ds# snap set onlyoffice-ds onlyoffice.ds-ssl-port=444
root@nc:/var/snap/onlyoffice-ds# snap logs onlyoffice-ds.nginx
2020-09-28T06:02:29Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:02:29Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
2020-09-28T06:02:30Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:02:30Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
2020-09-28T06:02:30Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:02:30Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
2020-09-28T06:02:31Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:02:31Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
2020-09-28T06:02:31Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:02:31Z onlyoffice-ds.nginx[346145]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
root@nc:/var/snap/onlyoffice-ds# snap restart onlyoffice-ds
Restarted.
root@nc:/var/snap/onlyoffice-ds# snap logs onlyoffice-ds.nginx
2020-09-28T06:03:00Z onlyoffice-ds.nginx[347432]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:03:00Z onlyoffice-ds.nginx[347432]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
2020-09-28T06:03:00Z onlyoffice-ds.nginx[347432]: nginx: [emerg] still could not bind()
2020-09-28T06:03:00Z systemd[1]: snap.onlyoffice-ds.nginx.service: Main process exited, code=exited, status=1/FAILURE
2020-09-28T06:03:00Z systemd[1]: snap.onlyoffice-ds.nginx.service: Failed with result 'exit-code'.
2020-09-28T06:03:00Z systemd[1]: snap.onlyoffice-ds.nginx.service: Scheduled restart job, restart counter is at 6.
2020-09-28T06:03:00Z systemd[1]: Stopped Service for snap application onlyoffice-ds.nginx.
2020-09-28T06:03:00Z systemd[1]: Started Service for snap application onlyoffice-ds.nginx.
2020-09-28T06:03:00Z onlyoffice-ds.nginx[347672]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2020-09-28T06:03:00Z onlyoffice-ds.nginx[347672]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)

`

I confirm there is a problem, tell me who and how could solve it

**Comment by barracuda7** [comment] 2020-10-18 04:35
I was able to permanently change the HTTPS port by editing this file:
10/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl

**Comment by pabloVoorvaart** [comment] 2020-10-26 11:59
I can confirm that what @barracuda7 said is true.
I edited /var/snap/onlyoffice-ds/10/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl 
and then restarted the snap.

**Comment by DejfCold** [comment] 2021-02-06 23:04
I can't talk about Ubuntu, but Debian 10 works fine. I'd expect those two would behave the same here.

**Comment by tj0xin** [comment] 2022-02-06 14:20
@barracuda7 @pabloVoorvaart 
I have installed document server as (built from source) and wanted to change HTTPS port (443) to (9443) so when https://docserver.domain.com is entered it should be redirected to 9443 port. instead for 443.

Tested when the 443 is blocked with UFW it doesnt load the webpage, without 443 Blocked in UFW it works. 

Am i doing something incorrect or there is something else where i need to change the port?

I have these 3 files, 1.ds.conf  2.ds.conf.tmpl  3.ds-ssl.conf.tmpl

Below is my ds-ssl.conf.tmpl: 

## HTTPS host
server {
  listen 0.0.0.0:9443 ssl;
  listen [::]:9443 ssl default_server;
 # server_tokens off;
  server_name www.docserver.domain.com docserver.domain.com;
  root /usr/share/nginx/html;

  ## Strong SSL Security
  ## https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
  ssl on;

**Comment by parolkar** [comment] 2023-04-30 14:26
> +1 (on Ubuntu 18.04) Workaround may be to edit the ds.conf manually.

This wont work because the ds.conf gets re-written

**Comment by igwyd** [comment] 2023-11-16 11:13
Hello @Andy-EOS, sorry for the late reply, now it work, you can change HTTPS port like this https://github.com/ONLYOFFICE/snap-documentserver#running-onlyoffice-document-server-on-different-ssl-port

**Comment by Rita-Bubnova** [comment] 2024-01-18 11:41
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-01-18 11:41 UTC
Labels: question

**Comment by avdddd1111** [comment] 2024-05-16 09:14
Hello @poltpolt ! In your problem, port 80 is occupied.
If you want to change port 80, try: `snap set onlyoffice-ds onlyoffice.ds-port=8888`
